package GUI;

import Code.FileHandler;
import Code.GeneralUser;
import Code.User;

import javax.swing.*;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

public class UserSignup {
    private JPanel rootPanel;
    private JTextField nameField;
    private JTextField emailField;
    private JPasswordField passwordField;
    private JTextField phoneField;
    private JTextField addressField;
    private JTextField dobField;
    private JButton signupButton;
    private JButton backButton;
    private JLabel nameLabel;
    private JLabel emailLabel;
    private JLabel passwordLabel;
    private JLabel phoneLabel;
    private JLabel addressLabel;
    private JLabel dobLabel;

    public UserSignup(ArrayList<GeneralUser> users, JPanel cardPanel, CardLayout cardLayout) {
        $$$setupUI$$$(); // Auto-generated by IntelliJ
        rootPanel = new JPanel();
        if (rootPanel == null) {
            throw new IllegalStateException("rootPanel is null. Ensure $$$setupUI$$$() is properly configured.");
        }

        // Setup layout for the rootPanel
        rootPanel.setLayout(new BorderLayout());
        rootPanel.add(createFormPanel(), BorderLayout.CENTER);

        // Signup Button Action Listener
        signupButton.addActionListener(e -> {
            try {
                String name = nameField.getText().trim();
                String email = emailField.getText().trim();
                String password = new String(passwordField.getPassword()).trim();
                String phone = phoneField.getText().trim();
                String address = addressField.getText().trim();
                Date dob = new SimpleDateFormat("dd-MM-yyyy").parse(dobField.getText().trim());

                // Validate Inputs
                if (!User.isValidName(name)) throw new IllegalArgumentException("Invalid Name.");
                if (!User.isValidEmail(email)) throw new IllegalArgumentException("Invalid Email.");
                if (!User.isValidPassword(password)) throw new IllegalArgumentException("Invalid Password.");
                if (!User.isValidPhoneNumber(phone)) throw new IllegalArgumentException("Invalid Phone.");

                // Create and save new user
                GeneralUser newUser = new GeneralUser(name, "U" + (users.size() + 1), password, email, phone, address, dob);
                users.add(newUser);
                FileHandler.saveToTextFile("users.txt", users);

                JOptionPane.showMessageDialog(rootPanel, "Signup Successful! User ID: " + newUser.getId());
                cardLayout.show(cardPanel, "Welcome");
                nameField.setText("");
                emailField.setText("");
                passwordField.setText("");
                phoneField.setText("");
                addressField.setText("");
                dobField.setText("");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPanel, "Error: " + ex.getMessage());
            }
        });

        // Back Button Action Listener
        backButton.addActionListener(e -> cardLayout.show(cardPanel, "Welcome"));
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    private JPanel createFormPanel() {
        JPanel formPanel = new JPanel();
        formPanel.setLayout(new GridLayout(8, 2, 10, 10));

        formPanel.add(nameLabel);
        formPanel.add(nameField);
        formPanel.add(emailLabel);
        formPanel.add(emailField);
        formPanel.add(passwordLabel);
        formPanel.add(passwordField);
        formPanel.add(phoneLabel);
        formPanel.add(phoneField);
        formPanel.add(addressLabel);
        formPanel.add(addressField);
        formPanel.add(dobLabel);
        formPanel.add(dobField);
        formPanel.add(signupButton);
        formPanel.add(backButton);

        return formPanel;
    }

    // Auto-generated UI initializer
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridBagLayout());

        nameLabel = new JLabel("Name:");
        nameField = new JTextField();

        emailLabel = new JLabel("Email:");
        emailField = new JTextField();

        passwordLabel = new JLabel("Password:");
        passwordField = new JPasswordField();

        phoneLabel = new JLabel("Phone:");
        phoneField = new JTextField();

        addressLabel = new JLabel("Address:");
        addressField = new JTextField();

        dobLabel = new JLabel("Date of Birth (dd-MM-yyyy):");
        dobField = new JTextField();

        signupButton = new JButton("Signup");
        backButton = new JButton("Back");
    }
}
